chat/urls.py
from django.urls import path
from . import views


app_name = 'chatApp'


urlpatterns = [
    path('', views.index, name="index"),
    path('<slug:room_name>/', views.chatroom, name="chatroom"),
    path('direct/<uuid:dm_user_id>/', views.directMessage, name="directMessage"),
]

chatroom/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/',include('chat.urls'))
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    unique_id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    image = models.FileField(upload_to='profile_pic', null=True)
    last_text = models.CharField(max_length=100)
    online_status = models.BooleanField(default=False)
    last_seen = models.DateTimeField(auto_now=True)


class ChatRoom(models.Model):
    name = models.CharField(max_length=100, null=True)
    slug = models.SlugField(unique=True, null=True)
    room_id = models.CharField(max_length=64)       # storing sha256 string


class ChatMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    message_content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['created_at',]

class ChatNotification(models.Model):
    chat=models.ForeignKey(ChatMessage,on_delete=models.CASCADE)
    chat_sent_to=models.ForeignKey(User,on_delete=models.CASCADE)
    is_seen=models.BooleanField(default=False)

chat/views.py
from django.shortcuts import render
from chat.models import *
import hashlib
from django.http import HttpResponse
import os
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.hashers import check_password
from django.contrib.auth import authenticate

def is_firebase_admin_installed():
    try:
        import firebase_admin
        return True
    except :
        return "cannot initialize app"

#def make_password(password,salt=None,hasher='default'):

def index(request):
    
    friends = Profile.objects.exclude(user=request.user)
    curr_profile_user = Profile.objects.get(user=request.user)
    params = {
        'friends': friends,
        'curr_profile_user': curr_profile_user,
    }
    
    return render(request,"index.html",params)
        
    


def chatroom(request, room_name):
    chatroom = ChatRoom.objects.get(slug=room_name)     # get the room from the id provided user_id
    messages = ChatMessage.objects.filter(room=chatroom)
    friends = Profile.objects.exclude(user=request.user)

    params = {
        "room": chatroom,
        "messages": messages,
        'friends': friends
    }
    return render(request, 'index.html', params)


def getRoomId(user_id, dm_user_id):
    room_name = ""
    if str(user_id) > str(dm_user_id):
        room_name = f"{user_id}--{dm_user_id}"
    else:
        room_name = f"{dm_user_id}--{user_id}"

    #room_id = hashlib.sha256(room_name.encode()).hexdigest()
    room_id=make_password(room_name)
    print("django has made following id:")
    print(room_id)
    return room_id,room_name


def directMessage(request, dm_user_id): 
    print("dm user id is:")
   
    logged_in_user_id = Profile.objects.get(user=request.user).unique_id 
    room_id,room_name = getRoomId(logged_in_user_id, dm_user_id)
    print("room id is:")
    print(room_id)
    print("room name is:")
    print(room_name)
    ans=False
    rooms=ChatRoom.objects.all()
    for chat_room in rooms:
        if check_password(room_name,chat_room.room_id):
            receiver=Profile.objects.get(unique_id=dm_user_id)
            chatroom=chat_room
            messages=ChatMessage.objects.filter(room=chatroom)
            friends=Profile.objects.exclude(user=request.user)
            curr_profile_user=Profile.objects.get(user=request.user)
            ans=True
            print("room primary key is:")
            print(chatroom.id)
            # print("we are in encrypted function")
            # print("receiver username is:")
            # print(receiver.user.username)
            # print("room id is")
            # print(chatroom.room_id)
            # print("messages are:")
            # print(messages)
            break
           
    if not ans:
        ChatRoom.objects.create(room_id=make_password(room_name))
        print("chatroom created")


    # if not ChatRoom.objects.filter(room_id=room_id).exists():
    #     ChatRoom.objects.create(room_id=room_id)
    # receiver=Profile.objects.get(unique_id=dm_user_id)
    # chatroom = ChatRoom.objects.get(room_id=room_id)
    # messages = ChatMessage.objects.filter(room=chatroom)
    # friends = Profile.objects.exclude(user=request.user)
    # curr_profile_user = Profile.objects.get(user=request.user)

    params = {
        'room': chatroom,
        'messages': messages,
        'friends': friends,
        'receiver':receiver,
        'curr_profile_user': curr_profile_user,
        'room_name':room_name
    }

    return render(request, 'index.html', params)

templates/base.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta http-equiv='X-UA-Compatible' content='ie=edge'>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.0.13/css/all.css'
        integrity='sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp' crossorigin='anonymous'>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css'
        integrity='sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB' crossorigin='anonymous'>
    <title> {% block title %} {% endblock %}</title>
    {% block extra_css %} {% endblock %}
</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <div class="d-flex justify-content-center align-items-center">
                <img class="mr-4" style="width:50px;" src="https://cdn1.iconfinder.com/data/icons/email-color-set/24/Send_Mail_3_email_color_c-512.png" alt="">
                <a class="navbar-brand text-white" href="#">VChat</a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'chatApp:home' %}">Rooms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    {% block content %}
    {% endblock %}

    {% block extra_js %}
    {% endblock %}



    <script src='http://code.jquery.com/jquery-3.3.1.min.js'
        integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js'
        integrity='sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49'
        crossorigin='anonymous'></script>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js'
        integrity='sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T'
        crossorigin='anonymous'></script>
</body>

</html>

templates/chatApp/index2.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>WhatsApp Web</title>
</head>

<body>
    <div class="back-container">
        <div class="container-fluid front-container">
            <div class="back-top"></div>
            <div class="back-main"></div>
        </div>
        <div class="container front-container1">
            <div class="row chat-top">
                <div class="col-sm-4 border-right border-secondary">
                    <img src="{% static 'img/image-1.png' %}" alt="" class="profile-image rounded-circle">
                    <span class="float-right mt-2">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" /></svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-left-fill mx-3" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" /></svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mr-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" /> </svg>
                    </span>
                </div>
                <div class="col-sm-8">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex align-items-center justify-content-center">
                            <img src="{% static 'img/image-1.png' %}" alt="" class="profile-image  rounded-circle">
                            <span class="ml-2">Janmay </span>
                            <span class="ml-2 text-muted">online </span>
                        </div>

                        <div>
                            <span class="float-right mt-2">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" /> <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" /> </svg>
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mx-3" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" /></svg>
                            </span>
                        </div>
                    </div>

                </div>
            </div>

            <!-- Frields Slide Bar -->
            <div class="row">
                <div class="col-sm-4 contacts">
                    <div class="contact-table-scroll">
                        <div class="p-3">
                            {% for friend in friends %}
                            <a href="{% url 'chatApp:directMessage' friend.unique_id %}" class="text-dark" style="cursor: pointer; text-decoration: none;">
                                <div class="d-flex w-100 align-items-center justify-content-between mb-3 friends">
                                    <div class="d-flex justify-content-center align-items-center">
                                        <img src="{% static 'img/image-1.png' %}" alt="" class="mr-4 profile-image rounded-circle">
                                        <div>
                                            {{ friend.user.username }} <br> <small>achi chal rahi</small>
                                        </div>
                                    </div>
                                    <div><small>11:55 PM</small></div>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!-- Chat Messages -->
                <div class="col-sm-8 message-area">
                    <div class="d-flex flex-column h-100">
                        <div class="message-table-scroll">
                            <table class="table">
                                <tbody>
                                    <!-- Text Sent -->
                                    <tr>
                                    <td>
                                        <p class="bg-success float-right chat_message p-2 mt-2 mr-5 shadow-sm text-white rounded ">
                                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores, illo.
                                            <small class="ml-2" style="font-size: 12px; color:#8FBEA6;">11:21 PM</small>
                                        </p>
                                    </td>
                                    </tr>

                                    <!-- RECEIVED TEXT -->
                                    <tr>
                                    <td>
                                        <p class="bg-primary float-left chat_message p-2 mt-2 mr-5 shadow-sm text-white rounded ">
                                            Lorem ipsum dolor sit amet consectetur adipisicing.
                                            <small class="ml-2" style="font-size: 12px; color:#8FBEA6;">11:21 PM</small>
                                        </p>
                                    </td>
                                    </tr>

                                    {% for message in messages %}
                                        <tr>
                                        <td>
                                            <p class="bg-primary float-left chat_message p-2 mt-2 mr-5 shadow-sm text-white rounded ">
                                                {{ message.message_content }}
                                                <small class="ml-2" style="font-size: 12px; color:#8FBEA6;">{{ message.created_at }}</small>
                                            </p>
                                        </td>
                                        </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>

                        <!-- Message Box -->
                        <div class="row message-box p-3 mt-auto">
                            <div class="col-sm-2 mt-2">
                                <a href="">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" /> <path fill-rule="evenodd"     d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683z" /> <path     d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" /> </svg>
                                </a>
                                <a href="" class="link-document">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip mx-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z" /></svg>
                                </a>
                            </div>
                            <div class="col-sm-10">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="d-flex flex-row">
                                        <input class="form-control" id="message-input" type="text" name="message" placeholder="Write message...">
                                        <button class="btn btn-success"  id="send-button" type="submit"> Send</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>



    {{ room.room_id|json_script:"json-chatroom" }}
    {{ request.user.username|json_script:"json-username" }}

    <!-- <script src="{% static 'js/group-message.js' %}"></script> -->

    <!-- Option 1: Bootstrap Bundle with Popper.js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js" integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD" crossorigin="anonymous"></script>


</body>

</html>

templates/index.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>WhatsApp Web</title>
</head>

<body>
    <div class="back-container">
        <div class="container-fluid front-container">
            <div class="back-top"></div>
            <div class="back-main"></div>
        </div>
        <div class="container front-container1">
            <div class="row chat-top">
                <div class="col-sm-4 border-right border-secondary">
                    <img src="{% static 'img/image-1.png' %}" alt="" class="profile-image rounded-circle">
                    <span class="float-right mt-2">
                        <div class="notification">
                            <i class="fa fa-bell" aria-hidden="true"></i>
                            <span class="badge" id="count_badge"></span>
                        </div>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-left-fill mx-3"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mr-2"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                 d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                        </svg>
                    </span>
    
                </div>
                <div class="col-sm-8" id="receiver-name">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex align-items-center justify-content-center">
                            <img src="{% static 'img/image-1.png' %}" alt="" class="profile-image  rounded-circle">
                            <span class="ml-2">{{receiver.user.username}}  </span>
                            
                            {% if curr_profile_user.online_status %}
                            <span class="ml-2 text-muted">online </span>
                            {% endif %}
                        </div>

                        <div>
                            <span class="float-right mt-2">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" /> <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" /> </svg>
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mx-3" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" /></svg>
                            </span>
                        </div>
                    </div>

                </div>
            </div>

            <!-- Frields Slide Bar -->
            <div class="row">
                <div class="col-sm-4 contacts">
                    <div class="contact-table-scroll">
                        <div class="p-3">
                            {% for friend in friends %}
                            {{friend.username}}
                            <a href="{% url 'chatApp:directMessage' friend.unique_id %}" class="text-dark" style="cursor: pointer; text-decoration: none;">
                                <div class="d-flex w-100 align-items-center justify-content-between mb-3 friends">
                                    <div class="d-flex justify-content-center align-items-center">
                                        <img src="{% static 'img/image-1.png' %}" alt="" class="mr-4 profile-image rounded-circle">
                                        <div>
                                            {{ friend.user.username }} <br> <small>achi chal rahi</small>
                                        </div>
                                    </div>
                                    <div><small>11:55 PM</small></div>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!-- Chat Messages -->
                <div class="col-sm-8 message-area">
                    <div class="d-flex flex-column h-100">
                        <div class="message-table-scroll">
                            <table class="table" id="messagetable">
                                <tbody id="displayed_messages" style="overflow: scroll;">
                                   {% for message in messages %}
                                   {% if message.sender.username == request.user.username %}
                                    <tr>
                                    <td>
                                        <p class="bg-success float-right chat_message p-2 mt-2 mr-5 shadow-sm text-white rounded ">
                                            {{message.message_content}}
                                            <small class="ml-2" style="font-size: 12px; color:#8FBEA6;">11:21 PM</small>
                                        </p>
                                    </td>
                                    </tr> 
                                   
                                    {% else %}
                                    <tr>
                                        <td>
                                            <p class="bg-primary float-left chat_message p-2 mt-2 mr-5 shadow-sm text-white rounded ">
                                            
                                              {{message.message_content}}
                                            
                                                <small class="ml-2" style="font-size: 12px; color:#8FBEA6;">11:21 PM</small>
                                            </p>
                                        </td>  
                                        </tr>
                                    

                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        <!-- Message Box -->
                        <div class="row message-box p-3 mt-auto">
                            <div class="col-sm-2 mt-2">
                                <a href="">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" /> <path fill-rule="evenodd"     d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683z" /> <path     d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" /> </svg>
                                </a>
                                <a href="" class="link-document">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip mx-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd"     d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z" /></svg>
                                </a>
                            </div>
                            <div class="col-sm-10">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="d-flex flex-row">
                                        <input class="form-control" id="message-input" type="text" name="message" placeholder="Write message...">
                                        <button class="btn btn-success"  id="send-button" type="submit"> Send</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


   
    {{ room.room_id|json_script:"json-chatroom" }}
    {{ request.user.username|json_script:"json-username" }}
    {{ receiver.user.username|json_script:"json-receiver_username"}}
    {{ room.room_name|json_script:"json-roomname"}}
   
    <script src="{% static 'js/group-message.js' %}"></script>
    <script src="{% static 'js/isOnline.js' %}"></script>
    <!--<script src="{% static 'js/notify.js' %}"></script>-->



</body>

</html>